version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - .:/app
      - .:/app/node_modules
      - .:/app/.next
